config.value=You are in dev environment

spring.datasource.url=jdbc:postgresql://localhost:5432/categorydb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
