server:
    port: 9092
spring:
    application:
        name: quiz-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/quizz
eureka:
    client:
        registerWithEureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka